### ISSUE TITLE
Is JMX auth and SSL supported?

### ISSUE THREAD

**Issue by cin** [instaclustr/cassandra-sidecar#2]
I'm not seeing where you can inject credentials for JMX or truststore/keystore information in the sidecar. Is this supported?

**Comment by smiklosovic** [comment]
Hi @cin , yes, it is supported, it is available under these flags:

```
$ java -jar cassandra-sidecar-2.0.0-alpha4.jar cassandra-sidecar help
```

```
...
      --jmx-service=[ADDRESS][:PORT]|[JMX SERVICE URL]
                            Address (and optional port) of a Cassandra instance to connect to via JMX. ADDRESS may be a
                              hostname, IPv4 dotted or decimal address, or IPv6 address. When ADDRESS is omitted, the loopback
                              address is used. PORT, when specified, must be a valid port number. The default port 7199 will be
                              substituted if omitted.Defaults to ':7199'
      --jmx-user=[STRING]   User for JMX for Cassandra
      --jmx-password=[STRING]
                            Password for JMX for Cassandra
      --jmx-truststore=[PATH]
                            Path to truststore file for Cassandra
      --jmx-truststore-password=[PATH]
```

**Comment by cin** [comment]
Sorry, I should have been more specific. I meant through the service.

```yaml
{
    "type": "backup",
    "storageLocation": "s3://xxx",
    "snapshotTag": "hello",
    "entities": "system_auth",
    "k8sNamespace": "xxx",
    "k8sSecretName": "xxx",
    "dataDirectory": "/var/lib/cassandra",
    "globalRequest": true
}
```
